### ISSUE TITLE
Error during login

### ISSUE THREAD

**Issue by nr458h** [EugeneTheDev/TaigaMobile#7]
Hi all

first: thanks for the app and making it open source

At the moment I cannot use it, because after entering my credentials I get the error

> error during login. Check credentials or connection

I use lineage OS without play services and afwall.

The provider of the taiga instance is board.disroot.org (I already checked if I made any typos)

Thanks for help in advance

**Comment by EugeneTheDev** [comment]
Hello. Do you enter host address without protocol (`board.disroot.org`, not `https://board.disroot.org/`)? Also, can you please attach log file? You can find it inside `./Android/data/io.eugenethedev.taigamobile/files/logs/` folder

**Comment by nr458h** [comment]
Thanks for the quick response
I tried both with and without

Find the logs attached, it seems that the connection is refuesed by the server

Sorry don't know how to make it collapsable at the phone ;)

> Do. Mai 13 2021 at 01:40:31:446 PM : LoginViewModel$login - 31 - java.net.UnknownHostException: Unable to resolve host "https": No address associated with hostname 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124) 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103) 	at java.net.InetAddress.getAllByName(InetAddress.java:1152) 	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49) 	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164) 	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129) 	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71) 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205) 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221) 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 	at io.eugenethedev.taigamobile.dagger.DataModule$provideTaigaApi$$inlined$-addInterceptor$1.intercept(OkHttpClient.kt:1081) 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 	at java.lang.Thread.run(Thread.java:919) Do. Mai 13 2021 at 04:03:39:901 PM : MainActivity$onCreate - 87 - Color(0.07058824, 0.07058824, 0.07058824, 1.0, sRGB IEC61966-2.1) Do. Mai 13 2021 at 04:04:22:778 PM : LoginViewModel$login - 31 - retrofit2.HttpException: HTTP 400 	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53) 	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:150) 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 	at java.lang.Thread.run(Thread.java:919) Do. Mai 13 2021 at 04:06:21:874 PM : LoginViewModel$login - 31 - retrofit2.HttpException: HTTP 400 	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53) 	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:150) 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 	at java.lang.Thread.run(Thread.java:919)

**Comment by EugeneTheDev** [comment]
This is really strange. I've tried to log in to this server (see screenshot, I don't have account here, so I've entered dumb login/password). And connection seems OK (of course it returns error 400 because login and password is incorrect, but connection is fine).  What logs say is that you're entering only `https` in host field, so app is trying to connect to this host (which is obviously would cause error).   
  
If the problem still persists, please provide more info about your device (OS version, vendor) 
  
<img width=400 src="https://user-images.githubusercontent.com/36568187/118234106-91900f00-b49b-11eb-96fe-283287037bf2.png">

**Comment by nr458h** [comment]
Hi @EugeneTheDev 
Thanks for looking into this

Today I tried with the newest version and it still does not work - but if I put a https in front of the adress it does not do anything at all

Here are the logs from today
Sa. Mai 15 2021 at 08:36:32:639 PM : MainActivity$onCreate - 87 - Color(0.07058824, 0.07058824, 0.07058824, 1.0, sRGB IEC61966-2.1) Sa. Mai 15 2021 at 08:36:32:690 PM : MainActivity$onCreate - 87 - Color(0.07058824, 0.07058824, 0.07058824, 1.0, sRGB IEC61966-2.1) Sa. Mai 15 2021 at 08:37:57:543 PM : LoginViewModel$login - 31 - retrofit2.HttpException: HTTP 400 	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53) 	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:150) 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 	at java.lang.Thread.run(Thread.java:919) Sa. Mai 15 2021 at 08:40:25:671 PM : LoginViewModel$login - 31 - retrofit2.HttpException: HTTP 400 	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53) 	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:150) 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 	at java.lang.Thread.run(Thread.java:919) 



You asked for more information
I'm using Lineageos 17 with Magisk Manager and afwall+ in whitelist mode
The phone is a oneplus 7pro

**Comment by EugeneTheDev** [comment]
Can you please try debug version of the app (it will provide more detailed logs, just don't add part with your login and password here)  [TaigaMobile-1.2.1-debug.apk.zip](https://github.com/EugeneTheDev/TaigaMobile/files/6495932/TaigaMobile-1.2.1-debug.apk.zip). Also, if you have account can you try global Taiga instance? (https://tree.taiga.io, hostname of the server is `api.taiga.io`)

**Comment by itsarectangle** [comment]
Same prob here, tried everything, cant login

**Comment by EugeneTheDev** [comment]
I've tested app with global and local taiga instances, and everything was fine. Please note, that you need to use Taiga login and password (e.g. if you've signed up to Taiga via GitHub you cannot enter GitHub credentials, only Taiga credentials). Can you please try debug version of the app (which I've provided above) and check in app logs that request contains correct login/password? Or, if you have access to Taiga server logs, can you review request body there?

**Comment by AtriLahiji** [comment]
Ahhh, so I use LDAP as a login provider. That might be it...

**Comment by itsarectangle** [comment]
Tried a second phone, Pixel 4 w/ CalyxOS, I enter my info when logging into app, click continue and nothing.  Hangs.

**Comment by EugeneTheDev** [comment]
@itsarectangle If you've installed debug app, can you check app logs whether auth request contains correct credentials? Also, please note what I've written above, that you can use **only Taiga credentials**

**Comment by itsarectangle** [comment]
> 
> 
> @itsarectangle If you've installed debug app, can you check app logs whether auth request contains correct credentials? Also, please note what I've written above, that you can use **only Taiga credentials**

Sure, see below.  Looks like it's trying port 443, and my Taiga server is only set up for http.

Wed Jun 02 2021 at 11:18:35:355 AM : LoginViewModel$login - 31 - java.net.ConnectException: Failed to connect to taiga.***.***/***.***.***:443
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at io.eugenethedev.taigamobile.dagger.DataModule$provideTaigaApi$$inlined$-addInterceptor$1.intercept(OkHttpClient.kt:1081)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.net.ConnectException: failed to connect to taiga.***.***/***.***.*** (port 443) from /192.168.1.106 (port 48870) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
	at libcore.io.IoBridge.isConnected(IoBridge.java:287)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:192)
	at libcore.io.IoBridge.connect(IoBridge.java:134)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	... 22 more
Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
	at libcore.io.IoBridge.isConnected(IoBridge.java:274)
	... 32 more

**Comment by EugeneTheDev** [comment]
Interesting, thanks. For security reasons I do not allow cleartext traffic from app (so only `https://...` allowed). But I think I should add port input on login screen

**Comment by EugeneTheDev** [comment]
I've added ability to specify port on login screen. Also, I've tweaked UI on login screen a little bit. So it should be easier to understand what is expected in each field. Since there were no activity, I'm closing this issue

**Comment by fam4r** [comment]
Still not able to login to `board.disroot.org:443`

**Comment by darhma** [comment]
I am also experiencing the same problem logging in to https://board.disroot.org or https://board.disroot.org:443 

App version: 1.5.3 (f-droid)
Android version: 11 (lineageos 18.1)
Log: `gio set 30 2021 at 01:44:31:006 AM : LoginViewModel$login - 41 - retrofit2.HttpException: HTTP 400 
	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)`

**Comment by fam4r** [comment]
Hey, just a feedback after the update of the app.
Now it works and I can login on the Taiga instance on Disroot.
Thank you!

**Comment by darhma** [comment]
@fam4r What version has worked for you? I use version 1.5.3 downloaded from f-droid and it doesn't work for me.

**Comment by EugeneTheDev** [comment]
@darhma please note that I do not manage f-droid releases by myself. It is managed by some volunteer, apparently. You can always find the latest versions in this repository Releases or on Google Play. The latest version for now is 1.5.4

**Comment by darhma** [comment]
@EugeneTheDev Thanks, I'm familiar with how f-droid works, I didn't realize the new version was released. 
It usually takes a few days for the update to arrive on f-droid.
I will wait, thanks again for solving the problem and for your work
